### PR TITLE
Terrain handling for 1.17/1.18 & Bugs fix for “ClickWindow“ packet

### PR DESCRIPTION
**Pull request by BruceChenQAQ**
* Terrain handling for 1.17/1.17.* and 1.18/1.18.*
  * chunk loading progress will show in the "/move" command
  * using /move when chunk is not fully loaded can take a long time to calculate Path
* Verify that the network packets changed in 1.16.5 through 1.18.2 are processed correctly.
* Bugs fix for “ClickWindow“ packet
  * initial inventory
  * initial inventory
  * click test
  * click test
  * drop test
  * drop test

### CODE REVIEW

**Comment by milutinke** [comment]
There is a crash when you try to throw a single item, it you do `/inventory player drop 36 all` then it works.
image

Happens here
image

**Comment by BruceChenQAQ** [comment]
> There is a crash when you try to throw a single item, it you do `/inventory player drop 36 all` then it works. image
> 
> Happens here image

tried to fix in https://github.com/milutinke/Minecraft-Console-Client/pull/2/commits/cbe348555b91fadd11db0f0d60fc1e75eef1dd35

**Comment by milutinke** [comment]
Works, awesome

**Comment by BruceChenQAQ** [comment]
There are still bugs of the same type, try to fix them in the next commit.
(Fixed in https://github.com/milutinke/Minecraft-Console-Client/pull/2/commits/a18b526a417652dac42527e33db1df2c5da02b35)

**Comment by milutinke** [comment]
I've resolved the conflict.
Let's test everything once more so we're sure that everything is working as intended.
I'll use the farming bot to test it all in action.

**Comment by BruceChenQAQ** [comment]
If the player's HitBox is not completely inside a single block when moving with the command “/move X Y Z”, illegal movement packets may appear (player HitBox colliding with solid block) and will be ignored by the server.

In this case, the bot may travel a long distance instantaneously.

fixed in https://github.com/milutinke/Minecraft-Console-Client/pull/2/commits/94fd8b118de50caa9863b8e9f73b024e1d491ff8

**Comment by milutinke** [comment]
Once you think everything has been tested and working, tell me so I can merge and clean up my code and tell Orelio to review the PR.
Awesome work, very excited to use the terrain movement again.
If you have some time, you can take a look at 1.19 branch if you want to help out, I'm doing a port to 1.19, it's not completely functional.

**Comment by BruceChenQAQ** [comment]
Did some tests and it should all work fine.
Next, I'll look into the part about message handling in 1.19 😊

**Pull request merged**
